.\" Copyright (c) 1980, 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)swapon.8	6.3 (Berkeley) 3/16/91
.\"
.\" Japanese Version Copyright (c) 1997 NAKANO Takeo all rights reserved.
.\" Translated Thu Aug 21 1997 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated & Modified Thu 7 Oct 1999 by NAKANO Takeo 
.\" Updated & Modified Wed 14 Jun 2000 by NAKANO Takeo 
.\" Updated & Modified Wed May  5 13:08:03 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\" Updated & Modified Mon May  9 03:47:14 JST 2005 by Yuichi SATO
.\" Updated & Modified Fri Apr  3 02:01:12 JST 2020
.\"         by Yuichi SATO <ysato444@ybb.ne.jp>
.\"
.TH SWAPON 8 "October 2014" "util-linux" "System Administration"
.\"O .SH NAME
.\"O swapon, swapoff \- enable/disable devices and files for paging and swapping
.SH 名前
swapon, swapoff \- デバイスやファイルへのページング、スワッピングを有効 / 無効にする
.\"O .SH SYNOPSIS
.SH 書式
.B swapon
[options]
.RI [ specialfile ...]
.br
.B swapoff
.RB [ \-va ]
.RI [ specialfile ...]
.\"O .SH DESCRIPTION
.SH 説明
.\"O .B swapon
.\"O is used to specify devices on which paging and swapping are to take place.
.B swapon
は、ページング (paging) やスワッピング (swapping) を行うデバイスを
指定するために用いられる。

.\"O The device or file used is given by the
.\"O .I specialfile
.\"O parameter.  It may be of the form
.\"O .BI \-L " label"
.\"O or
.\"O .BI \-U " uuid"
.\"O to indicate a device by label or uuid.
使用されるデバイスまたはファイルは、
.I specialfile
引き数で指定される。
.BI \-L " label"
または
.BI \-U " uuid"
という形式で、ラベルまたは uuid でデバイスを指定することができる。

.\"O Calls to
.\"O .B swapon
.\"O normally occur in the system boot scripts making all swap devices available, so
.\"O that the paging and swapping activity is interleaved across several devices and
.\"O files.
.B swapon
の呼び出しは、通常システムのブートスクリプトで行われる。
普通はここですべてのスワップデバイスを有効にし、ページング
やスワッピングが複数のデバイスやファイルにまたがってインターリーブ 
(interleave) 動作できるようにする。

.\"O Normally, the first form is used:
通常は
.B swapon \-a
の書式で実行されることが多い。
.TP

.B swapoff
disables swapping on the specified devices and files.
When the
.B \-a
flag is given, swapping is disabled on all known swap devices and files
(as found in
.I /proc/swaps
or
.IR /etc/fstab ).

.\"O .SH OPTIONS
.SH オプション
.TP
.BR \-a , " \-\-all"
.\"O All devices marked as ``swap'' in
.\"O .I /etc/fstab
.\"O are made available, except for those with the ``noauto'' option.
.\"O Devices that are already being used as swap are silently skipped.
.I /etc/fstab
中で ``swap'' マークが付いているスワップデバイスをすべて有効にする。
ただし ``noauto'' オプションが付いているものは除く。
スワップとして既に使われているデバイスは、黙ってスキップされる。
.TP
.BR \-d , " \-\-discard" [ =\fIpolicy\fR]
Enable swap discards, if the swap backing device supports the discard or
trim operation.  This may improve performance on some Solid State Devices,
but often it does not.  The option allows one to select between two
available swap discard policies:
.B \-\-discard=once
to perform a single-time discard operation for the whole swap area at swapon;
or
.B \-\-discard=pages
to asynchronously discard freed swap pages before they are available for reuse.
If no policy is selected, the default behavior is to enable both discard types.
The
.I /etc/fstab
mount options
.BR discard ,
.BR discard=once ,
or
.B discard=pages
may also be used to enable discard flags.
.TP
.BR \-e , " \-\-ifexists"
.\"O Silently skip devices that do not exist.
.\"O The
.\"O .I /etc/fstab
.\"O mount option
.\"O .B nofail
.\"O may also be used to skip non-existing device.
存在しないデバイスを黙ってスキップする。
The
.I /etc/fstab
mount option
.B nofail
may also be used to skip non-existing device.

.TP
.BR \-f , " \-\-fixpgsz"
Reinitialize (exec mkswap) the swap space if its page size does not
match that of the current running kernel.
.BR mkswap (2)
initializes the whole device and does not check for bad blocks.
.TP
.BR \-h , " \-\-help"
.\"O Display help text and exit.
ヘルプを表示して、終了する。
.TP
.BI \-L " label"
.\"O Use the partition that has the specified
.\"O .IR label .
.\"O (For this, access to
.\"O .I /proc/partitions
.\"O is needed.)
指定された
.I label
のパーティションを使う。
(これを使用するためには
.I /proc/partitions
にアクセスする必要がある。)
.TP
.BR \-o , " \-\-options " \fIopts\fP
Specify swap options by an fstab-compatible comma-separated string.
For example:
.RS
.RS
.sp
.B "swapon -o pri=1,discard=pages,nofail /dev/sda2"
.sp
.RE
The \fIopts\fP string is evaluated last and overrides all other
command line options.
.RE
.TP
.BR \-p , " \-\-priority " \fIpriority\fP
.\"O Specify the priority of the swap device.
スワップデバイスの優先度 (priority) を指定する。
.\"O .I priority
.\"O is a value between \-1 and 32767.  Higher numbers indicate
.\"O higher priority.  See
.\"O .BR swapon (2)
.\"O for a full description of swap priorities.  Add
.\"O .BI pri= value
.\"O to the option field of
.\"O .I /etc/fstab
.\"O for use with
.\"O .BR "swapon -a" .
.I priority
は \-1 から 32767 の間の数値である。
数値が大きいほど優先度が高い。
スワップ優先度の詳細な説明に関しては
.BR swapon (2)
を見よ。
.I /etc/fstab
のオプションフィールドに
.BI pri= value
を記述すれば、
.B "swapon -a" 
の際にその値が用いられる。
.\"O When no priority is defined, it defaults to \-1.
優先度が定義されていない場合、デフォルトは \-1 である。
.TP
.BR \-s , " \-\-summary"
.\"O Display swap usage summary by device.  Equivalent to "cat /proc/swaps".
.\"O This output format is DEPRECATED in favour
.\"O of \fB\-\-show\fR that provides better control on output data.
スワップの使用状況をデバイス毎に表示する。
"cat /proc/swaps" と等しい。
This output format is DEPRECATED in favour
of \fB\-\-show\fR that provides better control on output data.
.TP
.BR \-\-show [ =\fIcolumn\fR ...]
Display a definable table of swap areas.  See the
.B \-\-help
output for a list of available columns.
.TP
.B \-\-output\-all
Output all available columns.
.TP
.B \-\-noheadings
Do not print headings when displaying
.B \-\-show
output.
.TP
.B \-\-raw
Display
.B \-\-show
output without aligning table columns.
.TP
.B \-\-bytes
Display swap size in bytes in
.B \-\-show
output instead of in user-friendly units.
.TP
.BI \-U  " uuid"
.\"O Use the partition that has the specified
.\"O .IR uuid .
指定された
.I uuid
のパーティションを使う。
.TP
.BR \-v , " \-\-verbose"
.\"O Be verbose.
詳細に表示する。
.TP
.BR \-V , " \-\-version"
.\"O Display version information and exit.
バージョン情報を表示して、終了する。
.\"O .SH NOTES
.SH 注意
.\"O .SS Files with holes
.SS ホールのあるファイル
The swap file implementation in the kernel expects to be able to write to the
file directly, without the assistance of the filesystem.  This is a problem on
files with holes or on copy-on-write files on filesystems like Btrfs.
.sp
Commands like
.BR cp (1)
or
.BR truncate (1)
create files with holes.  These files will be rejected by swapon.
.sp
Preallocated files created by
.BR fallocate (1)
may be interpreted as files with holes too depending of the filesystem.
Preallocated swap files are supported on XFS since Linux 4.18.
.sp
The most portable solution to create a swap file is to use
.BR dd (1)
and /dev/zero.
.SS Btrfs
Swap files on Btrfs are supported since Linux 5.0 on files with nocow attribute.
See the
.BR btrfs (5)
manual page for more details.
.SS NFS
.\"O Swap over \fBNFS\fR may not work.
\fBNFS\fR 上の swap は動作しないかもしれない。
.SS Suspend
.B swapon
automatically detects and rewrites a swap space signature with old software
suspend data (e.g. S1SUSPEND, S2SUSPEND, ...). The problem is that if we don't
do it, then we get data corruption the next time an attempt at unsuspending is
made.
.\"O .SH ENVIRONMENT
.SH 環境変数
.IP LIBMOUNT_DEBUG=all
.\"O enables libmount debug output.
libmount デバッグ出力を有効にする。
.IP LIBBLKID_DEBUG=all
.\"O enables libblkid debug output.
libblkid デバッグ出力を有効にする。

.\"O .SH SEE ALSO
.SH 関連項目
.BR swapoff (2),
.BR swapon (2),
.BR fstab (5),
.BR init (8),
.BR fallocate (1),
.BR mkswap (8),
.BR mount (8),
.BR rc (8)
.\"O .SH FILES
.SH ファイル
.br
.I /dev/sd??
.\"O standard paging devices
標準のページングデバイス
.br
.I /etc/fstab
.\"O ascii filesystem description table
ファイルシステムを ascii で記述した表。
.\"O .SH HISTORY
.SH 履歴
.\"O The
.\"O .B swapon
.\"O command appeared in 4.0BSD.
.B swapon
コマンドは 4.0BSD から導入された。
.\"O .SH AVAILABILITY
.SH 入手方法
.\"O The swapon command is part of the util-linux package and is available from
.\"O https://www.kernel.org/pub/linux/utils/util-linux/.
swapon コマンドは util-linux パッケージの一部であり、
https://www.kernel.org/pub/linux/utils/util-linux/
から入手できる。
