.\"
.\" Japanese Version Copyright (c) 2019 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Jul  7 21:59:10 JST 2019
.\"         by Yuichi SATO <ysato444@ybb.ne.jp>
.\"
.TH PIDSTAT 1 "JULY 2018" Linux "Linux User's Manual" -*- nroff -*-
.\"O .SH NAME
.SH 名前
.\"O pidstat \- Report statistics for Linux tasks.
pidstat \- Linux タスクの統計をレポートする。
.\"O .SH SYNOPSIS
.SH 書式
.B pidstat [ -d ] [ -H ] [ -h ] [ -I ] [ -l ] [ -R ] [ -r ] [ -s ] [ -t ] [ -U [
.I username
.B ] ] [ -u ] [ -V ] [ -v ]
.B [ -w ] [ -C
.I comm
.B ] [ -G
.I process_name
.B ] [ --dec={ 0 | 1 | 2 } ] [ --human ] [ -p {
.I pid
.B [,...] | SELF | ALL } ] [ -T { TASK | CHILD | ALL } ] [
.I interval
.B [
.I count
.B ] ] [ -e
.I program
.I args
.B ]
.\"O .SH DESCRIPTION
.SH 説明
.\"O The
.\"O .B pidstat
.\"O command is used for monitoring individual tasks currently being managed
.\"O by the Linux kernel.
.B pidstat
コマンドは Linux カーネルで現在管理されている各タスクをモニタリングする。
.\"O It writes to standard output activities for every task selected with option
.\"O .B -p
.\"O or for every task managed by the Linux kernel if option
.\"O .B -p ALL
.\"O has been used. Not selecting any tasks is equivalent to specifying
.\"O .B -p ALL
.\"O but only active tasks (tasks with non-zero statistics values)
.\"O will appear in the report.
このコマンドは
.B -p
オプションで選択されたタスク、または
.B -p ALL
オプションが指定された場合は Linux カーネルが管理するすべてのタスクの活性度を、
標準出力に書き出す。
何も指定しないのは
.B -p ALL
を指定するのと同様であるが、
(統計値が 0 でない) アクティブなタスクのみが、レポートに現れる。

.\"O The
.\"O .B pidstat
.\"O command can also be used for monitoring the child processes of selected tasks.
.B pidstat
コマンドは選択されたタスクの子プロセスをモニタリングすることもできる。
.\"O Read about option
.\"O .B -T
.\"O below.
下記のオプション
.B -T
を参照すること。

.\"O The
.\"O .I interval
.\"O parameter specifies the amount of time in seconds between each report.
.\"O A value of 0 (or no parameters at all) indicates that tasks statistics are
.\"O to be reported for the time since system startup (boot).
.I interval
パラメータは各レポート間の時間を指定する。
値が 0 である (またはパラメータを指定しない) 場合、
システムのスタートアップ (ブート) からのタスクの統計をレポートする。
.\"O The
.\"O .I count
.\"O parameter can be specified in conjunction with the
.\"O .I interval
.\"O parameter if this one is not set to zero. The value of
.\"O .I count
.\"O determines the number of reports generated at
.\"O .I interval
.\"O seconds apart. If the
.\"O .I interval
.\"O parameter is specified without the
.\"O .I count
.\"O parameter, the
.\"O .B pidstat
.\"O command generates reports continuously.
.I count
パラメータは
.I interval
パラメータと組み合わせて使われる。
.I count
パラメータが指定されると、
.I count
は
.I interval
秒ごとに生成される回数を決定する。
.I count
パラメータを指定せずに
.I interval
パラメータを指定すると、
.B pidstat
コマンドは連続してレポートを生成する。

.\"O You can select information about specific task activities using flags.
.\"O Not specifying any flags selects only CPU activity.
フラグを使って特定のタスクの活性度の情報を選択できる。
フラグを指定しない場合、CPU の活性度のみが選択される。

.\"O .SH OPTIONS
.SH オプション
.IP "-C comm"
.\"O Display only tasks whose command name includes the string
.\"O .IR comm .
コマンド名に文字列
.I comm
を含むタスクのみを表示する。
.\"O This string can be a regular expression.
文字列には正規表現を使うことができる。
.IP -d
.\"O Report I/O statistics (kernels 2.6.20 and later only).
.\"O The following values may be displayed:
I/O 統計をレポートする (カーネル 2.6.20 以降のみ)。
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B kB_rd/s
.RS
.\"O Number of kilobytes the task has caused to be read from disk
.\"O per second.
1 秒あたりにタスクがディスクから読み出したキロバイト数。
.RE

.B kB_wr/s
.RS
.\"O Number of kilobytes the task has caused, or shall cause to be
.\"O written to disk per second.
1 秒あたりにタスクがディスクへ書き出した、
または書き出そうとしたキロバイト数。
.RE

.B kB_ccwr/s
.RS
.\"O Number of kilobytes whose writing to disk has been cancelled by
.\"O the task. This may occur when the task truncates some
.\"O dirty pagecache. In this case, some IO which another task has
.\"O been accounted for will not be happening.
タスクによってディスクへの書き出しがキャンセルされた
キロバイト数。
これは、タスクがダーティなページキャッシュを切り詰める際に
発生する。
この場合、他のタスクからアナウンスされていた I/O が、発生しなくなる。
.RE

.B iodelay
.RS
.\"O Block I/O delay of the task being monitored,
.\"O measured in clock ticks. This metric includes the delays spent
.\"O waiting for sync block I/O completion and for swapin block I/O
.\"O completion.
モニタリングしているタスクのブロック I/O 遅延。
クロック ticks で計測する。
この指標は、同期ブロック I/O の完了と
スワップインブロック I/O の完了を、待つのに使った時間を含む。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE
.RE
.IP "--dec={ 0 | 1 | 2 }"
.\"O Specify the number of decimal places to use (0 to 2, default value is 2).
使用する小数点の位置を指定する (0 から 2 で、デフォルトは 2 である)。
.IP "-e program args"
.\"O Execute
.\"O .IR program
.\"O with given arguments
.\"O .IR args
.\"O and monitor it with
.\"O .B pidstat.
.I program
を指定した引数
.I args
で実行し、
.B pidstat
でモニタリングする。
.\"O .B pidstat
.\"O stops when
.\"O .IR program
.\"O terminates.
.I program
が終了すると、
.B pidstat
も停止する。
.IP "-G process_name"
.\"O Display only processes whose command name includes the string
.\"O .IR process_name .
コマンド名が文字列
.I process_name
を含むプロセスのみを表示する。
.\"O This string can be a regular expression. If option -t is used
.\"O together with option -G then the threads belonging to that
.\"O process are also displayed (even if their command name doesn't
.\"O include the string
.\"O .IR process_name ).
文字列には正規表現を使うことができる。
オプション -t を、オプション -G とともに設定すると、
プロセスに属するスレッドも表示される
(コマンド名が文字列
.I process_name
を含んでいない場合にも表示される)。
.IP -H
.\"O Display timestamp in seconds since the epoch.
タイムスタンプを紀元 (epoch) からの秒数で表示する。
.IP -h
.\"O Display all activities horizontally on a single line, with no
.\"O average statistics at the end of the report. This is
.\"O intended to make it easier to be parsed by other programs.
すべての活性度を横 1 列に表示し、レポートの最後に平均の統計情報を付けない。
これは他のプログラムで解析しやすくことを意図している。
.IP --human
.\"O Print sizes in human readable format (e.g. 1.0k, 1.2M, etc.)
.\"O The units displayed with this option supersede any other default units (e.g.
.\"O kilobytes, sectors...) associated with the metrics.
サイズを人間が読みやすいフォーマット (例えば 1.0k, 1.2M など) で表示する。
このオプションで表示される単位は、指標に紐付けられたデフォルトの単位
(例えば、キロバイト、セクターなど) を上書きする。
.IP -I
.\"O In an SMP environment, indicate that tasks CPU usage
.\"O (as displayed by option
.\"O .B -u
.\"O ) should be divided by the total number of processors.
SMP 環境において、(オプション
.B -u
で表示される) タスクの CPU 利用量を
総プロセッサ数で割る。
.IP -l
.\"O Display the process command name and all its arguments.
プロセスのコマンド名とすべての引数を表示する。
.IP "-p { pid [,...] | SELF | ALL }"
.\"O Select tasks (processes) for which statistics are to be reported.
選択されたタスク (プロセス) の統計をレポートする。
.\"O .I pid
.\"O is the process identification number. The
.\"O .B SELF
.\"O keyword indicates that statistics are to be reported for the
.\"O .B pidstat
.\"O process itself, whereas the
.\"O .B ALL
.\"O keyword indicates that statistics are to be reported for all the
.\"O tasks managed by the system.
.I pid
はプロセス識別番号である。
.B SELF
キーワードを指定すると、
.B pidstat
プロセス自身の統計をレポートする。
また、
.B ALL
キーワードを指定すると、システムで管理されている
全てのタスクの統計をレポートする。
.IP -R
.\"O Report realtime priority and scheduling policy information.
.\"O The following values may be displayed:
リアルタイム優先度とスケジューリングポリシーの情報をレポートする。
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B prio
.RS
.\"O The realtime priority of the task being monitored.
モニタリングされるタスクのリアルタイム優先度。
.RE

.B policy
.RS
.\"O The scheduling policy of the task being monitored.
モニタリングされるタスクのスケジューリングポリシー。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE
.RE
.IP -r
.\"O Report page faults and memory utilization.
ページフォールトとメモリ利用をレポートする。

.\"O When reporting statistics for individual tasks,
.\"O the following values may be displayed:
各タスクの統計をレポートする場合、以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B minflt/s
.RS
.\"O Total number of minor faults the task has made per second, those
.\"O which have not required loading a memory page from disk.
1 秒あたりのタスクが起こしたディスクからメモリへのロードを
必要としないマイナーフォールトの回数。
.RE

.B majflt/s
.RS
.\"O Total number of major faults the task has made per second, those
.\"O which have required loading a memory page from disk.
1 秒あたりのタスクが起こしたディスクからメモリへのロードを
必要としたメジャーフォールトの回数。
.RE

.B VSZ
.RS
.\"O Virtual Size: The virtual memory usage of entire task in kilobytes.
Virtual Size: タスク全体の仮想メモリの使用量 (キロバイト)
.RE

.B RSS
.RS
.\"O Resident Set Size: The non-swapped physical memory
.\"O used by the task in kilobytes.
Resident Set Size: タスクのスワップを含まない物理メモリの使用量 (キロバイト)
.RE

.B %MEM
.RS
.\"O The tasks's currently used share of available physical memory.
タスクの現在の使用可能物理メモリの利用率。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE

.\"O When reporting global statistics for tasks and all their children,
.\"O the following values may be displayed:
タスクとその子プロセスの全体統計のレポートでは、
以下の値が表示される。

.B UID
.RS
.\"O The real user identification number of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの識別番号。
.RE

.B minflt-nr
.RS
.\"O Total number of minor faults made by the task and all its children,
.\"O and collected during the interval of time.
計測期間にタスクとすべての子プロセスが起こした
マイナーフォールトの回数。
.RE

.B majflt-nr
.RS
.\"O Total number of major faults made by the task and all its children,
.\"O and collected during the interval of time.
計測期間にタスクとすべての子プロセスが起こした
メジャーフォールトの回数。
.RE

.B Command
.RS
.\"O The command name of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスのコマンド名。
.RE
.RE
.IP -s
.\"O Report stack utilization.
.\"O The following values may be displayed:
スタック使用状況をレポートする。
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B StkSize
.RS
.\"O The amount of memory in kilobytes reserved for the task as stack,
.\"O but not necessarily used.
タスクに予約されたスタックのメモリ量 (キロバイト)。
このメモリは必ず使われる訳ではない。
.RE

.B StkRef
.RS
.\"O The amount of memory in kilobytes used as stack, referenced by the task.
タスクが参照するスタックのメモリ量 (キロバイト)。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE
.RE
.IP "-T { TASK | CHILD | ALL }"
.\"O This option specifies what has to be monitored by the
.\"O .B pidstat
.\"O command. The
.\"O .B TASK
.\"O keyword indicates that statistics are to be reported for individual tasks
.\"O (this is the default option) whereas the
.\"O .B CHILD
.\"O keyword indicates that statistics are to be globally reported for the
.\"O selected tasks and all their children. The
.\"O .B ALL
.\"O keyword indicates that statistics are to be reported for
.\"O individual tasks and globally for the selected
.\"O tasks and their children.
このオプションは、
.B pidstat
コマンドで何をモニタリングするかを指定する。
.B TASK
キーワードを指定すると、各タスクの統計がレポートされる
(これがデフォルトオプションである)。
また
.B CHILD
キーワードを指定すると、各タスクとその子プロセスの統計が
レポートされる。
.B ALL
キーワードを指定すると、各タスクの統計と、
選択されたタスクと子プロセスの統計が表示される。

.\"O Note: Global statistics for tasks and all their children are not available
.\"O for all options of
.\"O .B pidstat.
注意: タスクとその子プロセスの全体の統計は
.B pidstat
のすべてのオプションを指定しても利用可能ではない。
.\"O Also these statistics are not necessarily relevant to current time interval:
これらの統計は現在の期間と関係をもつ必要がない。
.\"O The statistics of a child process are collected only when it finishes or
.\"O it is killed.
子プロセスの統計は、それが終了した場合、または kill された場合に収集される。
.IP -t
.\"O Also display statistics for threads associated with selected tasks.
選択されたタスクに紐付くスレッドの統計を表示する。

.\"O This option adds the following values to the reports:
このオプションは以下の値をレポートに追加する。

.B TGID
.RS
.RS
.\"O The identification number of the thread group leader.
スレッドグループリーダーの識別番号。
.RE

.B TID
.RS
.\"O The identification number of the thread being monitored.
モニタリングするスレッドの識別番号。
.RE
.RE
.IP "-U [ username ]"
.\"O Display the real user name of the tasks being monitored instead of the UID.
モニタリングするタスクの、UID の代わりに実ユーザ名を表示する。
.\"O If
.\"O .I username
.\"O is specified, then only tasks belonging to the specified user are displayed.
.I username
が指定されると、指定したユーザに紐付くタスクのみが表示される。
.IP -u
.\"O Report CPU utilization.
CPU 利用状況をレポートする。

.\"O When reporting statistics for individual tasks,
.\"O the following values may be displayed:
各タスクの統計をレポートする際、
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B %usr
.RS
.\"O Percentage of CPU used by the task while executing at the user level
.\"O (application), with or without nice priority. Note that this field
.\"O does NOT include time spent running a virtual processor.
nice 優先度なしでユーザレベル (アプリケーション) で実行された CPU 利用の割合。
このフィールドは仮想プロセッサで使われる時間を「含まない」。
.RE

.B %system
.RS
.\"O Percentage of CPU used by the task while executing at the system level
.\"O (kernel).
システムレベル (カーネル) で実行された CPU 利用の割合。
.RE

.B %guest
.RS
.\"O Percentage of CPU spent by the task in virtual machine (running a virtual
.\"O processor).
CPU が仮想マシンのタスク (仮想プロセッサの実行) に使った時間の割合。
.RE

.B %wait
.RS
.\"O Percentage of CPU spent by the task while waiting to run.
CPU がタスクの実行待ちに使った時間の割合。
.RE

.B %CPU
.RS
.\"O Total percentage of CPU time used by the task. In an SMP environment,
.\"O the task's CPU usage will be divided by the total number of CPU's if
.\"O option
.\"O .B -I
.\"O has been entered on the command line.
タスクに使った CPU 時間の合計の割合。
SMP 環境では、オプション
.B -I
がコマンドラインから指定された場合、
タスクの CPU 利用率は CPU の合計数で割られる。
.RE

.B CPU
.RS
.\"O Processor number to which the task is attached.
タスクがアタッチされたプロセッサ番号。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE

.\"O When reporting global statistics for tasks and all their children,
.\"O the following values may be displayed:
タスクとそのすべての子プロセスの全体の統計をレポートする場合、
以下の値が表示される。

.B UID
.RS
.\"O The real user identification number of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスの識別番号。
.RE

.B usr-ms
.RS
.\"O Total number of milliseconds spent
.\"O by the task and all its children while executing at the
.\"O user level (application), with or without nice priority, and
.\"O collected during the interval of time. Note that this field does
.\"O NOT include time spent running a virtual processor.
計測期間の間に、タスクとすべての子プロセスが、
ユーザレベル (アプリケーション) で実行され、
かつ nice 優先度あり、もしくはなしで実行された総時間 (ミリ秒)。
このフィールドは、仮想プロセッサの実行で使った
時間が「含まない」点に注意すること。
.RE

.B system-ms
.RS
.\"O Total number of milliseconds spent
.\"O by the task and all its children while executing at the
.\"O system level (kernel), and collected during the interval of time.
計測期間の間に、タスクとすべての子プロセスが、
システムレベル (カーネル) で実行された総時間 (ミリ秒)。
.RE

.B guest-ms
.RS
.\"O Total number of milliseconds spent
.\"O by the task and all its children in virtual machine (running a virtual
.\"O processor).
計測期間の間に、タスクとすべての子プロセスが、
(仮想プロセッサを実行する) 仮想マシンで実行された総時間 (ミリ秒)。
.RE

.B Command
.RS
.\"O The command name of the task which is being monitored
.\"O together with its children.
モニタリングされるタスクと子プロセスのコマンド名。
.RE
.RE
.IP -V
.\"O Print version number then exit.
バージョン番号を表示して、終了する。
.IP -v
.\"O Report values of some kernel tables. The following values may be displayed:
カーネルテーブルの値をレポートする。
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B threads
.RS
.\"O Number of threads associated with current task.
現在のタスクに紐付くスレッド数。
.RE

.B fd-nr
.RS
.\"O Number of file descriptors associated with current task.
現在のタスクに紐付くファイルディスクリプターの数。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE
.RE
.IP -w
.\"O Report task switching activity (kernels 2.6.23 and later only).
.\"O The following values may be displayed:
タスク切り替えの活性度をレポートする (カーネル 2.6.23 以降のみ)。
以下の値が表示される。

.B UID
.RS
.RS
.\"O The real user identification number of the task being monitored.
モニタリングされるタスクの実ユーザ識別番号。
.RE

.B USER
.RS
.\"O The name of the real user owning the task being monitored.
モニタリングされるタスクの実ユーザ名。
.RE

.B PID
.RS
.\"O The identification number of the task being monitored.
モニタリングされるタスクの識別番号。
.RE

.B cswch/s
.RS
.\"O Total number of voluntary context switches the task made per second.
.\"O A voluntary context switch occurs when a task blocks because it
.\"O requires a resource that is unavailable.
1 秒あたりにタスクが起こした自発的 (voluntary) な
コンテキストスイッチの回数。
自発的なコンテキストスイッチは、タスクブロックが必要とした
リソースが利用可能でない場合に発生する。
.RE

.B nvcswch/s
.RS
.\"O Total number of non voluntary context switches the task made per second.
1 秒あたりにタスクが起こした自発的でない
コンテキストスイッチの回数。
.\"O A involuntary context switch takes place when a task executes
.\"O for the duration of its time slice and then is forced to relinquish the
.\"O processor.
自発的でないコンテキストスイッチは、
タスクがタイムスライスの間で実行され、
強制的にプロセッサを放棄させられた場合に発生する。
.RE

.B Command
.RS
.\"O The command name of the task.
タスクのコマンド名。
.RE
.RE
.\"O .SH ENVIRONMENT
.SH 環境変数
.\"O The
.\"O .B pidstat
.\"O command takes into account the following environment variables:
.B pidstat
コマンドは以下の環境変数を扱う。

.IP S_COLORS
.\"O When this variable is set, display statistics in color on the terminal.
この環境変数を設定すると、端末上で統計をカラー表示する。
.\"O Possible values for this variable are
.\"O .IR never ,
.\"O .IR always
.\"O or
.\"O .IR auto
.\"O (the latter is the default).
この環境変数に指定可能な値は、
.IR never ,
.IR always ,
.I auto
である (最後がデフォルトである)。

.\"O Please note that the color (being red, yellow, or some other color) used to display a value
.\"O is not indicative of any kind of issue simply because of the color. It only indicates different
.\"O ranges of values.
値を表示する色 (赤、黄、またはその他の色) は、色によって何かの意味を示している訳ではない。
色は値の範囲を示しているだけである。

.IP S_COLORS_SGR
.\"O Specify the colors and other attributes used to display statistics on the terminal.
.\"O Its value is a colon-separated list of capabilities that defaults to
.\"O .BR H=31;1:I=32;22:M=35;1:N=34;1:Z=34;22 .
.\"O Supported capabilities are:
端末で統計を表示する際に、色とその他の属性を指定する。
この値は、コロン区切りの機能のリストで、デフォルトは
.B H=31;1:I=32;22:M=35;1:N=34;1:Z=34;22
である。
サポートされている機能は以下のとおり。

.RS
.TP
.B H=
.\"O SGR (Select Graphic Rendition) substring for percentage values greater than or equal to 75%.
割合が 75% 以上の場合の SGR (Select Graphic Rendition) 部分文字列。

.TP
.B I=
.\"O SGR substring for item values like PID, UID or CPU number.
PID, UID, CPU 番号などのアイテム値を表示する SGR 部分文字列。

.TP
.B M=
.\"O SGR substring for percentage values in the range from 50% to 75%.
割合が 50% から 75% の場合の SGR 部分文字列。

.TP
.B N=
.\"O SGR substring for non-zero statistics values and for tasks names.
0 以外の統計値とタスク名を表示する SGR 部分文字列。

.TP
.B Z=
.\"O SGR substring for zero values and for threads names.
0 とスレッド名を表示する SGR 部分文字列。
.RE

.IP S_TIME_FORMAT
.\"O If this variable exists and its value is
.\"O .BR ISO
.\"O then the current locale will be ignored when printing the date in the report header.
この環境変数が存在し、かつ値が
.B ISO
の場合、レポートのヘッダの日付を表示する際に、
現在のロケールを無視する。
.\"O The
.\"O .B pidstat
.\"O command will use the ISO 8601 format (YYYY-MM-DD) instead.
代わりに、
.B pidstat
コマンドは ISO 8601 フォーマット (YYYY-MM-DD) を使う。
.\"O The timestamp will also be compliant with ISO 8601 format.
タイムスタンプも ISO 8601 フォーマットに従う。
　　　　　　　　　　　　　　　　　　　　
.\"O .SH EXAMPLES
.SH 例
.B pidstat 2 5
.RS
.\"O Display five reports of CPU statistics for every active task in the system
.\"O at two second intervals.
システムのアクティブなタスクの CPU 統計を 2 秒間隔で 5 回レポートする。
.RE

.B pidstat -r -p 1643 2 5
.RS
.\"O Display five reports of page faults and memory statistics for
.\"O PID 1643 at two second intervals.
PID 1643 のページフォールトとメモリの統計を 2 秒間隔で 5 回レポートする。
.RE

.\"O .B pidstat -C """fox|bird"" -r -p ALL
.B pidstat -C """fox|bird""" -r -p ALL
.RS
.\"O Display global page faults and memory statistics for all the
.\"O processes whose command name includes the string "fox" or "bird".
コマンド名が文字列 "fox" または "bird" を含む
すべてのプロセスのページフォールトとメモリの統計を表示する。
.RE

.B pidstat -T CHILD -r 2 5
.RS
.\"O Display five reports of page faults statistics at two second intervals
.\"O for the child processes of all tasks in the system. Only child processes
.\"O with non-zero statistics values are displayed.
システムのすべてのタスクの子プロセスについて、
ページフォールトの統計を 2 秒間隔で 5 回レポートする。
統計値が 0 でない子プロセスのみが表示される。
.\"O .SH BUGS
.SH バグ
.\"O .I /proc
.\"O filesystem must be mounted for the
.\"O .B pidstat
.\"O command to work.
.B pidstat
コマンドが動作するためには、
.I /proc
ファイルシステムがマウントされていなければならない。

.\"O .SH FILES
.SH ファイル
.IR /proc
.\"O contains various files with system statistics.
システム統計を含むさまざまなファイルを保持する。

.\"O .SH AUTHOR
.SH 著者
Sebastien Godard (sysstat <at> orange.fr)
.\"O .SH SEE ALSO
.SH 関連項目
.BR sar (1),
.BR top (1),
.BR ps (1),
.BR mpstat (1),
.BR iostat (1),
.BR vmstat (8)

.I https://github.com/sysstat/sysstat

.I http://pagesperso-orange.fr/sebastien.godard/
