.\" Copyright (C) 1998-2004 Miquel van Smoorenburg.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
.\"
.\" Japanese Version Copyright (c) 2001 Maki KURODA
.\"     all right reserved,
.\" Translated Tue Nov  10 18:28:49 JST 2001
.\" by Maki KURODA <mkuroda@aisys-jp.com>
.\"
.TH "LAST, LASTB" "1" "October 2013" "util-linux" "User Commands"
.\"O .SH NAME
.SH 名前
.\"O last, lastb \- show a listing of last logged in users
last, lastb \- 最後にログインしたユーザのリストを表示する。
.\"O .SH SYNOPSIS
.SH 書式
.B last
[options]
.RI [ username "...] [" tty ...]
.br
.B lastb
[options]
.RI [ username "...] [" tty ...]
.\"O .SH DESCRIPTION
.SH 説明
.\"O .B last
.\"O searches back through the
.\"O .I /var/log/wtmp
.\"O file (or the file designated by the
.\"O .B \-f
.\"O option) and displays a list of all users logged in (and out) since that
.\"O file was created.  One or more
.\"O .IR usernames " and/or " ttys
.\"O can be given, in which case
.\"O .B last
.\"O will show only the entries matching those arguments.  Names of
.\"O .I ttys
.\"O can be abbreviated, thus
.\"O .B last 0
.\"O is the same as
.\"O .BR "last tty0" .
.B last
は
.I /var/log/wtmp
ファイル (または
.B \-f
オプションで指定されたファイル) を検索し、ファイルが作られてからの、
すべてのユーザのログイン (ログアウト) のリストを表示する。
1 つ以上の
.IR ユーザ名 " と/または " "端末 (tty)"
を指定可能で、この場合
.B last
は引数にマッチしたエントリのみを表示する。
.I "端末 (tty)"
の名前は省略可能であり、
.B last 0
は
.B "last tty0"
と同じである。
.PP
.\"O When catching a SIGINT signal (generated by the interrupt key, usually
.\"O control-C) or a SIGQUIT signal,
.\"O .B last
.\"O will show how far it has searched through the file; in the case of the
.\"O SIGINT signal
.\"O .B last
.\"O will then terminate.
SIGINT シグナル (割り込みキー、通常は control-C で生成される)、
または SIGQUIT シグナルをキャッチすると、
.B last
はファイルをどこまで検索したかを表示する。
そして、SIGINT シグナルの場合、
.B last
は終了する。
.PP
.\"O The pseudo user
.\"O .B reboot
.\"O logs in each time the system is rebooted.  Thus
.\"O .B last reboot
.\"O will show a log of all the reboots since the log file was created.
擬似ユーザ (pseudo user)
.B reboot
がシステムがリブートしたときにログインする。
よって
.B last reboot
でログファイルが作られてからのすべてのリブートが表示される。
.PP
.\"O .B lastb
.\"O is the same as
.\"O .BR last ,
.\"O except that by default it shows a log of the
.\"O .I /var/log/btmp
.\"O file, which contains all the bad login attempts.
.B lastb
は
.BR last
と同様であるが、デフォルトでは
.I /var/log/btmp
ファイルのログを表示する。
これには不正なログインの試みが記録されている。
.\"O .SH OPTIONS
.SH オプション
.TP
.BR \-a , " \-\-hostlast"
.\"O Display the hostname in the last column.  Useful in combination with the
.\"O .B \-\-dns
.\"O option.
ホスト名を最後の列に表示する。
.B \-\-dns
オプションと組み合わせて使うと便利である。
.TP
.BR \-d , " \-\-dns"
.\"O For non-local logins, Linux stores not only the host name of the remote
.\"O host, but its IP number as well.  This option translates the IP number
.\"O back into a hostname.
ローカルからのログインでない場合、Linux はリモートホストのホスト名だけではなく、
IP アドレスも記録する。
このオプションは、IP アドレスをホスト名に変換する。
.TP
.BR \-f , " \-\-file " \fIfile\fR
.\"O Tell
.\"O .B last
.\"O to use a specific \fIfile\fR instead of
.\"O .IR /var/log/wtmp .
.B last
に
.I /var/log/wtmp
の代わりに \fIfile\fP を使用させる。
.\"O The
.\"O .B \-\-file
.\"O option can be given multiple times, and all of the specified files will be
.\"O processed.
.B \-\-file
オプションは複数回指定できて、指定されたすべてのファイルが
処理される。
.TP
.BR \-F , " \-\-fulltimes"
.\"O Print full login and logout times and dates.
ログインとログアウトの時刻と日付を完全な形で表示する。
.TP
.BR \-i , " \-\-ip"
.\"O Like
.\"O .B \-\-dns ,
.\"O but displays the host's IP number instead of the name.
.B \-\-dns
と似ているが、ホスト名ではなく、IP アドレスを表示する。
.TP
.BI \- number
.TQ
.BR \-n , " -\-limit " \fInumber\fR
Tell
.B last
how many lines to show.
.TP
.BR \-p , " \-\-present " \fItime\fR
Display the users who were present at the specified time.  This is
like using the options
.BR \-\-since " and " \-\-until
together with the same \fItime\fR.
.TP
.BR \-R , " \-\-nohostname"
Suppresses the display of the hostname field.
.TP
.BR \-s , " \-\-since " \fItime\fR
Display the state of logins since the specified
.IR time .
This is useful, e.g., to easily determine who was logged in at a
particular time.  The option is often combined with
.BR \-\-until .
.TP
.BR \-t , " \-\-until " \fItime\fR
Display the state of logins until the specified
.IR time .
.TP
.BI \-\-time\-format " format"
Define the output timestamp
.I format
to be one of
.IR notime ,
.IR short ,
.IR full ,
or
.IR iso .
The
.I notime
variant will not print any timestamps at all,
.I short
is the default, and
.I full
is the same as the
.B \-\-fulltimes
option.  The
.I iso
variant will display the timestamp in ISO-8601 format.  The ISO format
contains timezone information, making it preferable when printouts are
investigated outside of the system.
.TP
.BR \-w , " \-\-fullnames"
Display full user names and domain names in the output.
.TP
.BR \-x , " \-\-system"
Display the system shutdown entries and run level changes.
.\"O .SH TIME FORMATS
.SH 時間の形式
.\"O The options that take the
.\"O .I time
.\"O argument understand the following formats:
.I time
引数を取るオプションでは、以下の形式が使用できる。
.TS
l2 l.
YYYYMMDDhhmmss
YYYY-MM-DD hh:mm:ss
.\"O YYYY-MM-DD hh:mm	(seconds will be set to 00)
YYYY-MM-DD hh:mm	(秒は 00 に設定される)
.\"O YYYY-MM-DD	(time will be set to 00:00:00)
YYYY-MM-DD	(時分秒は 00:00:00 に設定される)
.\"O hh:mm:ss	(date will be set to today)
hh:mm:ss	(日付は今日に設定される)
.\"O hh:mm	(date will be set to today, seconds to 00)
hh:mm	(日付は今日に設定され、秒は 00 に設定される)
now
.\"O yesterday	(time is set to 00:00:00)
yesterday	(時分秒は 00:00:00 に設定される)
.\"O today	(time is set to 00:00:00)
today	(時分秒は 00:00:00 に設定される)
.\"O tomorrow	(time is set to 00:00:00)
tomorrow	(時分秒は 00:00:00 に設定される)
+5min
-5days
.TE
.\"O .SH NOTES
.SH 注意
.\"O The files
.\"O .I wtmp
.\"O and
.\"O .I btmp
.\"O might not be found.  The system only logs information in these files if
.\"O they are present.  This is a local configuration issue.  If you want the
.\"O files to be used, they can be created with a simple
.\"O .BR touch (1)
.\"O command (for example,
.\"O .IR "touch /var/log/wtmp" ).
ファイル
.I wtmp
と
.I btmp
が見つからないかもしれない。
システムはこれらのファイルがある場合にのみ、情報を記録する。
これはローカルの設定の問題である。
これらのファイルを使いたい場合、単純に
.BR touch (1)
コマンドで作成すればよい
(例
.IR "touch /var/log/wtmp" )。
.\"O .SH FILES
.SH ファイル
/var/log/wtmp
.br
/var/log/btmp
.\"O .SH AUTHOR
.SH 著者
.MT miquels@cistron.nl
Miquel van Smoorenburg
.ME
.\"O .SH AVAILABILITY
.SH 入手方法
.\"O The last command is part of the util-linux package and is available from
.\"O .UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
.\"O Linux Kernel Archive
.\"O .UE .
last コマンドは、util-linux パッケージの一部であり、
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE
から入手できる。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR login (1),
.BR wtmp (5),
.BR init (8),
.BR shutdown (8)
