.\" This page is in the public domain
.\"
.\" Japanese Version Copyright (c) 2001-2019 Yuichi SATO
.\"         all rights reserved.
.\" Translated Mon Nov 19 20:49:19 JST 2001
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\" Updated & Modified Wed Aug 28 03:44:00 JST 2002 by Yuichi SATO
.\" Updated & Modified Thu Jul 25 21:06:59 JST 2019
.\"         by Yuichi SATO <ysato444@ybb.ne.jp>
.\"
.TH LINE 1 "July 2002" "util-linux" "User Commands"
.\"O .SH NAME
.SH 名前
.\"O line \- read one line
line \- 1 行を読み込む
.\"O .SH SYNOPSIS
.SH 書式
.B line
.\"O .SH DESCRIPTION
.SH 説明
.\"O The utility
.\"O .B line
.\"O copies one line (up to a newline) from standard input to standard output.
ユーティリティ
.B line
は標準入力から読み込んだ (改行文字 (newline) までの) 1 行 を
標準出力にコピーする。
.\"O It always prints at least a newline and returns an exit status of 1
.\"O on EOF or read error.
.B line
は EOF やリードエラーの場合でも、少なくとも常に改行文字は出力し、
終了ステータスとして 1 を返す。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR read (1)
.\"O .SH AVAILABILITY
.SH 入手方法
.\"O The line command is part of the util-linux package and is available from
.\"O https://www.kernel.org/pub/linux/utils/util-linux/.
line コマンドは、util-linux パッケージの一部であり、
https://www.kernel.org/pub/linux/utils/util-linux/
から入手できる。
