.\"
.\" Japanese Version Copyright (c) 2001-2002 Yuichi SATO
.\"         all rights reserved.
.\" Translated Mon Nov 19 21:46:46 JST 2001
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\" Updated & Modified Sun Mar 24 02:43:47 JST 2002 by Yuichi SATO
.\" Updated & Modified Wed Jul 31 13:32:40 JST 2019
.\"         by Yuichi SATO <ysato444@ybb.ne.jp>
.\"
.\"WORD:	typescript	写し
.\"WORD:	divisor		除数
.\"
.TH SCRIPTREPLAY 1 "September 2011" "util-linux" "User Commands"
.\"O .SH "NAME"
.SH 名前
.\"O scriptreplay \- play back typescripts, using timing information
scriptreplay \- タイミング情報を使って写し (typescript) を再生する
.\"O .SH "SYNOPSIS"
.SH 書式
.B scriptreplay
[options]
.RB [ \-t ]
.I timingfile
.RI [ typescript
.RI [ divisor ]]
.\"O .SH "DESCRIPTION"
.SH 説明
.\"O This program replays a typescript, using timing information to ensure that
.\"O output happens in the same rhythm as it originally appeared when the script
.\"O was recorded.
このプログラムはタイミング情報を使って写しを再生する。
このタイミング情報により、以前に script で記録したときと
同じリズムで出力が行われることが保証される。
.PP
.\"O The replay simply displays the information again; the programs
.\"O that were run when the typescript was being recorded are not run again.
再生は単純に情報を再度表示するだけである。
typescript が記録されたときに実行されたプログラムは、再度実行されない。
.\"O Since the same information is simply being displayed,
.\"O .B scriptreplay
.\"O is only guaranteed to work properly if run on the same type of
.\"O terminal the typescript was recorded on.  Otherwise, any escape characters
.\"O in the typescript may be interpreted differently by the terminal to
.\"O which
.\"O .B scriptreplay
.\"O is sending its output.
同じ情報を単純に表示するだけなので、
.B scriptreplay
は typescript が記録された端末と同じタイプの端末でしか、
正しく動くことが保証されない。
端末のタイプが異なると、
.B scriptreplay
が出力を送る端末で、typescript 中のエスケープ文字が異なって解釈される可能性がある。
.PP
.\"O The timing information is what
.\"O .BR script (1)
.\"O outputs to standard error if it is
.\"O run with the
.\"O .B \-t
.\"O parameter.
タイミング情報は、
.B \-t
パラメータをつけて
.BR script (1)
を実行したときに、標準エラーに出力される。
.PP
.\"O By default, the typescript to display is assumed to be named
.\"O .BR typescript ,
.\"O but other filenames may be specified, as the second parameter or with option
.\"O .BR \-s .
デフォルトでは、表示される写しは
.B typescript
という名前であると仮定されるが、
第 2 パラメータまたはオプション
.B \-s
で他のファイルを指定することもできる。
.PP
.\"O If the third parameter is specified, it is used as a speed-up multiplier.
.\"O For example, a speed-up of 2 makes
.\"O .B scriptreplay
.\"O go twice as fast, and a speed-up of 0.1 makes it go ten times slower
.\"O than the original session.
第 3 パラメータが指定された場合は、スピードアップの倍数として使われる。
例えばスピードアップ 2 を指定すると、
.B scriptreplay
は元のセッションの 2 倍の速度で再生する。
スピードアップ 0.1 を指定すると、10 倍遅く再生する。
.\"O .SH OPTIONS
.SH オプション
.\"O The first three options will override old-style arguments.
最初の 3 つのオプションは、古い形式の引き数を上書きする。
.TP
.BR \-t , " \-\-timing " \fIfile\fR
.\"O File containing \fBscript\fR's timing output.
\fBscript\fR のタイミング出力を保持するファイル
.TP
.BR \-s , " \-\-typescript " \fIfile\fR
.\"O File containing \fBscript\fR's terminal output.
\fBscript\fR の端末出力を保持するファイル
.TP
.BR \-d , " \-\-divisor " \fInumber\fR
.\"O Speed up the replay displaying this
.\"O .I number
.\"O of times.  The argument is a floating point number.  It's called divisor
.\"O because it divides the timings by this factor.
再生を指定した
.I number
でスピードアップする。
引き数は小数値である。
これは、タイミングをこの数を分母として割るので、除数 (divisor) と呼ばれる。
.TP
.BR \-m , " \-\-maxdelay " \fInumber\fR
.\"O Set the maximum delay between transcript updates to
.\"O .I number
.\"O of seconds.  The argument is a floating point number.  This can be used to
.\"O avoid long pauses in the transcript replay.
写し (transcript) の更新を最大で
.I number
秒まで待つ。
引き数は小数値である。
これは、写しの再生に長い時間待たせるのを避けるために使われる。
.TP
.BR \-V , " \-\-version"
.\"O Display version information and exit.
バージョン情報を表示して、終了する。
.TP
.BR \-h , " \-\-help"
.\"O Display help text and exit.
ヘルプを表示して、終了する。
.\"O .SH "EXAMPLE"
.SH 例
.nf
% script --timing=file.tm script.out
.\"O Script started, file is script.out
スクリプトを開始しました、ファイルは script.out です
% ls
<etc, etc>
% exit
.\"O Script done, file is script.out
スクリプトを終了しました、ファイルは script.out です
% scriptreplay --timing file.tm --typescript script.out
.nf
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR script (1)
.\"O .SH "COPYRIGHT"
.SH 著作権
Copyright \(co 2008 James Youngman
.br
Copyright \(co 2008 Karel Zak
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
.PP
Released under the GNU General Public License version 2 or later.
.\"O .SH "AUTHOR"
.SH 著者
.\"O The original
.\"O .B scriptreplay
.\"O program was written by
元々の
.B scriptreplay
プログラムは
.MT joey@\:kitenet.net
Joey Hess
.\"O .ME .
.ME
によって書かれた。
.\"O The program was re-written in C by
このプログラムは
.MT jay@\:gnu.org
James Youngman
.ME
.\"O and
と
.MT kzak@\:redhat.com
Karel Zak
.\"O .ME .
.ME
によって C 言語で書き直された。
.\"O .SH AVAILABILITY
.SH 入手方法
.\"O The scriptreplay command is part of the util-linux package and is available from
.\"O .UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
.\"O Linux Kernel Archive
.\"O .UE .
scriptreplay コマンドは、util-linux パッケージの一部であり、
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE
から入手できる。
